name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set image version (tag)
       id: image version
       run: echo "gitsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: login to Registry 
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/mkodeh2024/express-docker:${{steps.image_version.outputs.gitsha}}
    - name: publish docker images
      run: docker push ghcr.io/mkodeh2024/express-docker:${{steps.image_version.outputs.gitsha}}
